### ISSUE TITLE
Multiple tests fail due to depending on exact SDL2 version

### ISSUE THREAD

**Issue by mgorny** [marcusva/py-sdl2#115]
```
======================================================================
FAIL: test_SDL_GetVersion (version_test.SDLVersionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/PySDL2-0.9.6/work/PySDL2-0.9.6/sdl2/test/version_test.py", line 28, in test_SDL_GetVersion
    self.assertEqual(v.patch, 6)
AssertionError: 7 != 6
```

Apparently because I have libsdl2 2.0.7. I don't think it's really helpful to anyone to require very specific SDL2 patch version.

**Comment by mgorny** [comment]
Same with sdlmixer_test:

```
======================================================================
FAIL: test_Mix_Linked_Version (sdlmixer_test.SDLMixerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/portage/dev-python/PySDL2-0.9.6/work/PySDL2-0.9.6/sdl2/test/sdlmixer_test.py", line 30, in test_Mix_Linked_Version
    self.assertEqual(v.contents.patch, 1)
AssertionError: 2 != 1
```
