### ISSUE TITLE
could not find function 'SDL_LoadFile_RW'

### ISSUE THREAD

**Issue by tomasantunes** [marcusva/py-sdl2#125]
I'm trying to run the hello world example on ubuntu and I get this error.

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import sdl2.ext
  File "/usr/local/lib/python3.5/dist-packages/sdl2/__init__.py", line 5, in <module>
    from .audio import *
  File "/usr/local/lib/python3.5/dist-packages/sdl2/audio.py", line 6, in <module>
    from .rwops import SDL_RWops, SDL_RWFromFile
  File "/usr/local/lib/python3.5/dist-packages/sdl2/rwops.py", line 54, in <module>
    SDL_LoadFile_RW = _bind("SDL_LoadFile_RW", [POINTER(SDL_RWops), POINTER(c_size_t), c_int], c_void_p)
  File "/usr/local/lib/python3.5/dist-packages/sdl2/dll.py", line 87, in bind_function
    (funcname, self._dll))
ValueError: could not find function 'SDL_LoadFile_RW' in <CDLL 'libSDL2-2.0.so.0', handle 26dc990 at 0x7f50791ea908>

**Comment by marcusva** [comment]
Which version of the SDL2 library is installed on your system?
If you built and installed SDL2 manually, which build flags did you use?

**Comment by tomasantunes** [comment]
I'm using PySDL2 0.9.6 and SDL 2.0.4

**Comment by tomasantunes** [comment]
thanks, that was it.
